[package]
name = "select"
version = "0.6.1"
authors = ["Utkarsh Kukreti <utkarshkukreti@gmail.com>"]
edition = "2021"
description = "A library to extract useful data from HTML documents, suitable for web scraping."
license = "MIT"
documentation = "https://docs.rs/select"
homepage = "https://github.com/utkarshkukreti/select.rs"
repository = "https://github.com/utkarshkukreti/select.rs"
exclude = [
    "/benches_/",
    "/examples/",
    "/tests/",
    "/.github/",
]

[dependencies]
bit-set = "0.8.0"
html5ever = { git = "https://github.com/servo/html5ever", package = "html5ever", rev = "b93afc9484cf5de40b422a44f9cea86ab371e3ee" } # html5ever = "0.27.0"
markup5ever_rcdom = { git = "https://github.com/servo/html5ever", package = "markup5ever_rcdom", rev = "b93afc9484cf5de40b422a44f9cea86ab371e3ee" } # markup5ever_rcdom = "0.3.0"

[dev-dependencies]
speculate = "0.1.2"

[[bin]]
name = "benchmarks"
path = "nightly_benches/benches.rs"